name: Trigger auto deployment for sample-ai-agent

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/sample-ai-agent-AutoDeployTrigger-a06f1698-865a-4342-833b-2424553fa0a6.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.SAMPLEAIAGENT_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.SAMPLEAIAGENT_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.SAMPLEAIAGENT_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: 
          registryUsername: ${{ secrets.SAMPLEAIAGENT_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SAMPLEAIAGENT_REGISTRY_PASSWORD }}
          containerAppName: sample-ai-agent
          resourceGroup: rg-ephraimvcabanlit-2254_ai
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


